#version 450

layout (local_size_x = 16, local_size_y = 16) in;

layout (rgba16f, set = 0, binding = 0) uniform image2D uImage;

layout (push_constant) uniform constants
{
    vec4 data1, data2, data3, data4;
} uPushConstants;

void main()
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(uImage);

    if (texelCoord.x >= size.x || texelCoord.y >= size.y)
        return;

    bool verticalLine = gl_LocalInvocationID.x == 0;
    bool horizontalLine = gl_LocalInvocationID.y == 0;

    if (verticalLine || horizontalLine)
        imageStore(uImage, texelCoord, uPushConstants.data1);
}
